/*TABLA DE HECHOS UNION ENTRE DOCUMENTO Y SUS MOVIMIENTOS*/

/*---Sistema contpaqi comercial premium V 11.5.1----
Creado por Luis Ramos
Fecha de creación 16/04/2026*/

SELECT Doc.CIDDOCUMENTO,Doc.CFECHA AS FECHA,Doc.CIDCLIENTEPROVEEDOR AS IDCLIENTE,Mov.CIDPRODUCTO,
Doc.CSERIEDOCUMENTO AS SERIE_ID, Mov.CUNIDADESCAPTURADAS AS CANTIDAD,Mov.CPRECIO,
(Mov.CUNIDADESCAPTURADAS * ISNULL(T6.CFACTORCONVERSION, 1)) AS KG,Doc.CTIPOCAMBIO,
(Mov.CIMPUESTO1 + Mov.CIMPUESTO2 + Mov.CIMPUESTO3) AS IMPUESTO,
(Mov.CDESCUENTO1 +Mov.CDESCUENTO2 + Mov.CDESCUENTO3 + Mov.CDESCUENTO4 +Mov.CDESCUENTO5) AS DESCUENTO,Mov.CNETO,Mov.CTOTAL
FROM [dbo].[admDocumentos] AS Doc
INNER JOIN [dbo].[admMovimientos] AS Mov ON Mov.CIDDOCUMENTO = Doc.CIDDOCUMENTO
LEFT JOIN [dbo].[admConversionesUnidad] AS T6 ON T6.CIDUNIDAD1 = Mov.CIDUNIDAD AND T6. CIDUNIDAD2 =2
WHERE Doc.CCANCELADO = 0 AND Doc.CIDDOCUMENTODE = 4 AND Doc.CSERIEDOCUMENTO NOT IN ('RE','')
